<a href="https://colab.research.google.com/github/Gurumultimedia/AnwarBachtiar.github.io/blob/main/Modul_6_Tugas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><img src="https://i.ibb.co.com/Z1c53Y0d/Gemini-Generated-Image-ojkf1iojkf1iojkf-1.png">

# Modul 6 - Tugas
Mentor: M. Ketsar Ali

<hr>

Kerjakan setiap pertanyaan dan upload hasil pengerjaan tugas ke link berikut:<br>
https://docs.google.com/forms/d/e/1FAIpQLSew1Do5X7XyYPE5DVI9vucgovd-pVQy7Jp8Kx_ToTll-HTA5w/viewform

<br>

### **Tulis nama lengkap Anda:**

Nama :Anwar Bachtiar

<br>

<div class="alert alert-success alertsuccess" style="margin-top: 20px">
    <b>[Tips]</b>: Sesulit apapun tantangan, seorang programmer dapat tumbuh optimal dengan belajar dari kesalahan dan pantang menyerah!
</div>

<br>

<br><br>

Untuk menyelesaikan tugas, silakan gunakan file dari google drive di link berikut:

https://drive.google.com/file/d/1tQDUuNPg0t7OIeZnRX9srySfqh6ecHPp/view?usp=sharing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

<br>

Lakukan tahapan *data cleaning* untuk dataset di link tersebut sehingga hasilnya menjadi persis seperti berikut:

<img src="https://www.megabagus.id/wp-content/uploads/2024/08/tugas-8.jpg" alt="tugas-8" border="0">

<br>

In [4]:
!pip install pandas
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Latihan_preprocessing_lv2.csv')
df

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

,Gender,Race,Birth_Year,Marital_Status,Years_on_Internet,Hours_Per_Day,Preferred_Browser,Preferred_Search_Engine,Preferred_Email,Read_News,Online_Shopping,Online_Gaming,Facebook,Twitter,Other_Social_Network
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,NaN
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,IG
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,NaN,Y,N,Insta
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,NaN
5,M,African American,1982,D,15,4,Internet Explorer,Google,Yahoo,Y,N,Y,N,N,NaN
6,M,African American,1981,D,11,2,Firefox,Google,Yahoo,10,Y,765,Y,Y,LinkedIn
7,M,White,1977,S,3,3,Internet Explorer,Yahoo,Yahoo,Y,NaN,NaN,Y,99,LinkedIn
8,F,African American,1969,M,6,2,Firefox,Google,Gmail,N,Y,N,N,N,NaN
9,M,White,1987,S,12,1,Safari,Yahoo,Yahoo,Y,9,Y,Y,N,MySpace
10,F,Hispanic,1959,D,12,5,Chrome,Google,Gmail,Y,N,N,Y,N,Google+

In [12]:
#Lihat Struktur Awal
df.info()
df.head()
df.columns = df.columns.str.strip()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   11 non-null     object
 1   Race                     11 non-null     object
 2   Birth_Year               11 non-null     int64
 3   Marital_Status           11 non-null     object
 4   Years_on_Internet        11 non-null     int64
 5   Hours_Per_Day            11 non-null     int64
 6   Preferred_Browser        11 non-null     object
 7   Preferred_Search_Engine  11 non-null     object
 8   Preferred_Email          11 non-null     object
 9   Read_News                11 non-null     object
 10  Online_Shopping          10 non-null     object
 11  Online_Gaming            9 non-null      object
 12  Facebook                 11 non-null     object
 13  Twitter                  11 non-null     object
 14  Other_Social_Network     11 non-null     object
dtypes: int64(3), object(12)
memory usage: 1.4+ KB

In [8]:
# Bersihkan Nama Kolom, Hilangkan spasi dan rapikan penamaan
df.columns = df.columns.str.strip()
df

,Gender,Race,Birth_Year,Marital_Status,Years_on_Internet,Hours_Per_Day,Preferred_Browser,Preferred_Search_Engine,Preferred_Email,Read_News,Online_Shopping,Online_Gaming,Facebook,Twitter,Other_Social_Network
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,NaN
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,IG
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,NaN,Y,N,Insta
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,NaN
5,M,African American,1982,D,15,4,Internet Explorer,Google,Yahoo,Y,N,Y,N,N,NaN
6,M,African American,1981,D,11,2,Firefox,Google,Yahoo,10,Y,765,Y,Y,LinkedIn
7,M,White,1977,S,3,3,Internet Explorer,Yahoo,Yahoo,Y,NaN,NaN,Y,99,LinkedIn
8,F,African American,1969,M,6,2,Firefox,Google,Gmail,N,Y,N,N,N,NaN
9,M,White,1987,S,12,1,Safari,Yahoo,Yahoo,Y,9,Y,Y,N,MySpace
10,F,Hispanic,1959,D,12,5,Chrome,Google,Gmail,Y,N,N,Y,N,Google+

In [11]:
# Tangani Missing Value, Dari gambar, kolom “Lainnya” menggunakan nilai "Kosong"
df['Other_Social_Network'] = df['Other_Social_Network'].fillna('Kosong')

df.fillna({
    'Preferred_Email': 'Unknown',
    'Preferred_Browser': 'Unknown'
}, inplace=True)

print(df.head())

  Gender              Race  Birth_Year Marital_Status  Years_on_Internet  \
0      M             White        1972              M                  8
1      M          Hispanic        1981              S                 14
2      F  African American        1977              S                  6
3      F             White        1961              D                  8
4      M             White        1954              M                  2

   Hours_Per_Day  Preferred_Browser Preferred_Search_Engine Preferred_Email  \
0              1            Firefox                  Google           Yahoo
1              2             Chrome                  Google         Hotmail
2              2            Firefox                   Yahoo           Yahoo
3              6            Firefox                  Google         Hotmail
4              3  Internet Explorer                    Bing         Hotmail

  Read_News Online_Shopping Online_Gaming Facebook Twitter  \
0         Y               N             N        Y       N
1         Y               N             N        Y       N
2         Y               Y           NaN        Y       N
3         N               Y             N        N       Y
4         Y               Y             N        Y       N

  Other_Social_Network
0               Kosong
1                   IG
2                Insta
3            Instagram
4               Kosong

In [13]:
df

,Gender,Race,Birth_Year,Marital_Status,Years_on_Internet,Hours_Per_Day,Preferred_Browser,Preferred_Search_Engine,Preferred_Email,Read_News,Online_Shopping,Online_Gaming,Facebook,Twitter,Other_Social_Network
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,Kosong
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,IG
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,NaN,Y,N,Insta
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,Kosong
5,M,African American,1982,D,15,4,Internet Explorer,Google,Yahoo,Y,N,Y,N,N,Kosong
6,M,African American,1981,D,11,2,Firefox,Google,Yahoo,10,Y,765,Y,Y,LinkedIn
7,M,White,1977,S,3,3,Internet Explorer,Yahoo,Yahoo,Y,NaN,NaN,Y,99,LinkedIn
8,F,African American,1969,M,6,2,Firefox,Google,Gmail,N,Y,N,N,N,Kosong
9,M,White,1987,S,12,1,Safari,Yahoo,Yahoo,Y,9,Y,Y,N,MySpace
10,F,Hispanic,1959,D,12,5,Chrome,Google,Gmail,Y,N,N,Y,N,Google+

In [14]:
# Ambil semua kolom kategorik/object .mode()
kolom_kategorik = df.select_dtypes(include='object').columns

# Isi kolom kosong  dengan modus
for col in kolom_kategorik:
    modus = df[col].mode()[0]
    df[col] = df[col].fillna(modus)

# Cek hasil
print(df.isnull().sum())

Gender                     0
Race                       0
Birth_Year                 0
Marital_Status             0
Years_on_Internet          0
Hours_Per_Day              0
Preferred_Browser          0
Preferred_Search_Engine    0
Preferred_Email            0
Read_News                  0
Online_Shopping            0
Online_Gaming              0
Facebook                   0
Twitter                    0
Other_Social_Network       0
dtype: int64

In [15]:
df

,Gender,Race,Birth_Year,Marital_Status,Years_on_Internet,Hours_Per_Day,Preferred_Browser,Preferred_Search_Engine,Preferred_Email,Read_News,Online_Shopping,Online_Gaming,Facebook,Twitter,Other_Social_Network
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,Kosong
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,IG
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,N,Y,N,Insta
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,Kosong
5,M,African American,1982,D,15,4,Internet Explorer,Google,Yahoo,Y,N,Y,N,N,Kosong
6,M,African American,1981,D,11,2,Firefox,Google,Yahoo,10,Y,765,Y,Y,LinkedIn
7,M,White,1977,S,3,3,Internet Explorer,Yahoo,Yahoo,Y,Y,N,Y,99,LinkedIn
8,F,African American,1969,M,6,2,Firefox,Google,Gmail,N,Y,N,N,N,Kosong
9,M,White,1987,S,12,1,Safari,Yahoo,Yahoo,Y,9,Y,Y,N,MySpace
10,F,Hispanic,1959,D,12,5,Chrome,Google,Gmail,Y,N,N,Y,N,Google+

In [16]:
# Seragamkan penulisan sosial media
df['Other_Social_Network'] = df['Other_Social_Network'].replace({
    'IG': 'Instagram',
    'Insta': 'Instagram',
    'instagram': 'Instagram'
})

# Lihat hasil
print(df[['Other_Social_Network']].head(10))

  Other_Social_Network
0               Kosong
1            Instagram
2            Instagram
3            Instagram
4               Kosong
5               Kosong
6             LinkedIn
7             LinkedIn
8               Kosong
9              MySpace

In [18]:
# Kolom kategorik
col = 'Other_Social_Network'

# Jadikan angka menjadi NaN
df[col] = df[col].replace(r'^\d+$', np.nan, regex=True)

# Isi NaN dengan modus
modus = df[col].mode()[0]
df[col] = df[col].fillna(modus)

# Lihat hasil
print(df[col].unique())
df

['Kosong' 'Instagram' 'LinkedIn' 'MySpace' 'Google+']

,Gender,Race,Birth_Year,Marital_Status,Years_on_Internet,Hours_Per_Day,Preferred_Browser,Preferred_Search_Engine,Preferred_Email,Read_News,Online_Shopping,Online_Gaming,Facebook,Twitter,Other_Social_Network
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,Kosong
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,Instagram
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,N,Y,N,Instagram
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,Kosong
5,M,African American,1982,D,15,4,Internet Explorer,Google,Yahoo,Y,N,Y,N,N,Kosong
6,M,African American,1981,D,11,2,Firefox,Google,Yahoo,10,Y,765,Y,Y,LinkedIn
7,M,White,1977,S,3,3,Internet Explorer,Yahoo,Yahoo,Y,Y,N,Y,99,LinkedIn
8,F,African American,1969,M,6,2,Firefox,Google,Gmail,N,Y,N,N,N,Kosong
9,M,White,1987,S,12,1,Safari,Yahoo,Yahoo,Y,9,Y,Y,N,MySpace
10,F,Hispanic,1959,D,12,5,Chrome,Google,Gmail,Y,N,N,Y,N,Google+

In [21]:
# Ganti nama kolom dengan bahasa Indonesia
df = df.rename(columns={
    'Gender': 'Kelamin',
    'Race': 'Ras',
    'Birth_Year': 'TTL',
    'Marital_Status': 'Status',
    'Years_on_Internet': 'Durasi',
    'Hours_Per_Day': 'Jam',
    'Preferred_Browser': 'Browser',
    'Preferred_Search_Engine': 'Search',
    'Preferred_Email': 'Email',
    'Read_News': 'News',
    'Online_Shopping': 'Shopping',
    'Online_Gaming': 'Gaming',
    'Other_Social_Network': 'Lainnya'
})

#Lihat Struktur Akhir
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Kelamin   11 non-null     object
 1   Ras       11 non-null     object
 2   TTL       11 non-null     int64
 3   Status    11 non-null     object
 4   Durasi    11 non-null     int64
 5   Jam       11 non-null     int64
 6   Browser   11 non-null     object
 7   Search    11 non-null     object
 8   Email     11 non-null     object
 9   News      11 non-null     object
 10  Shopping  11 non-null     object
 11  Gaming    11 non-null     object
 12  Facebook  11 non-null     object
 13  Twitter   11 non-null     object
 14  Lainnya   11 non-null     object
dtypes: int64(3), object(12)
memory usage: 1.4+ KB

,Kelamin,Ras,TTL,Status,Durasi,Jam,Browser,Search,Email,News,Shopping,Gaming,Facebook,Twitter,Lainnya
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,Kosong
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,Instagram
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,N,Y,N,Instagram
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,Kosong

In [26]:
kolom_yn = ['News', 'Shopping', 'Gaming', 'Facebook', 'Twitter']

for kolom in kolom_yn:

    # Ambil data valid
    data_valid = df[df[kolom].isin(['Y', 'N'])][kolom]

    # Cari modus
    modus = data_valid.mode()[0]

    # Ganti selain Y/N dengan modus
    df.loc[~df[kolom].isin(['Y', 'N']), kolom] = modus

In [30]:
# Simpan hasil data cleaning ke file CSV baru
df.to_csv('hasil_preprocessing.csv', index=False)

print("File berhasil disimpan")


# Memastikan file tersimpan
import os
print(os.listdir())
df

File berhasil disimpan
['.config', 'hasil_preprocessing.csv', 'Latihan_preprocessing_lv2.csv', 'sample_data']

,Kelamin,Ras,TTL,Status,Durasi,Jam,Browser,Search,Email,News,Shopping,Gaming,Facebook,Twitter,Lainnya
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,Kosong
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,Instagram
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,N,Y,N,Instagram
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,Kosong
5,M,African American,1982,D,15,4,Internet Explorer,Google,Yahoo,Y,N,Y,N,N,Kosong
6,M,African American,1981,D,11,2,Firefox,Google,Yahoo,Y,Y,N,Y,Y,LinkedIn
7,M,White,1977,S,3,3,Internet Explorer,Yahoo,Yahoo,Y,Y,N,Y,N,LinkedIn
8,F,African American,1969,M,6,2,Firefox,Google,Gmail,N,Y,N,N,N,Kosong
9,M,White,1987,S,12,1,Safari,Yahoo,Yahoo,Y,Y,Y,Y,N,MySpace
10,F,Hispanic,1959,D,12,5,Chrome,Google,Gmail,Y,N,N,Y,N,Google+

In [27]:
   df

,Kelamin,Ras,TTL,Status,Durasi,Jam,Browser,Search,Email,News,Shopping,Gaming,Facebook,Twitter,Lainnya
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,Kosong
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,Instagram
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,N,Y,N,Instagram
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,Kosong
5,M,African American,1982,D,15,4,Internet Explorer,Google,Yahoo,Y,N,Y,N,N,Kosong
6,M,African American,1981,D,11,2,Firefox,Google,Yahoo,Y,Y,N,Y,Y,LinkedIn
7,M,White,1977,S,3,3,Internet Explorer,Yahoo,Yahoo,Y,Y,N,Y,N,LinkedIn
8,F,African American,1969,M,6,2,Firefox,Google,Gmail,N,Y,N,N,N,Kosong
9,M,White,1987,S,12,1,Safari,Yahoo,Yahoo,Y,Y,Y,Y,N,MySpace
10,F,Hispanic,1959,D,12,5,Chrome,Google,Gmail,Y,N,N,Y,N,Google+

In [31]:
# Simpan hasil data cleaning ke file CSV baru
df.to_csv('hasil_preprocessing.csv', index=False)

print("File berhasil disimpan")


# Memastikan file tersimpan
import os
print(os.listdir())
df

File berhasil disimpan
['.config', 'hasil_preprocessing.csv', 'Latihan_preprocessing_lv2.csv', 'sample_data']

,Kelamin,Ras,TTL,Status,Durasi,Jam,Browser,Search,Email,News,Shopping,Gaming,Facebook,Twitter,Lainnya
0,M,White,1972,M,8,1,Firefox,Google,Yahoo,Y,N,N,Y,N,Kosong
1,M,Hispanic,1981,S,14,2,Chrome,Google,Hotmail,Y,N,N,Y,N,Instagram
2,F,African American,1977,S,6,2,Firefox,Yahoo,Yahoo,Y,Y,N,Y,N,Instagram
3,F,White,1961,D,8,6,Firefox,Google,Hotmail,N,Y,N,N,Y,Instagram
4,M,White,1954,M,2,3,Internet Explorer,Bing,Hotmail,Y,Y,N,Y,N,Kosong
5,M,African American,1982,D,15,4,Internet Explorer,Google,Yahoo,Y,N,Y,N,N,Kosong
6,M,African American,1981,D,11,2,Firefox,Google,Yahoo,Y,Y,N,Y,Y,LinkedIn
7,M,White,1977,S,3,3,Internet Explorer,Yahoo,Yahoo,Y,Y,N,Y,N,LinkedIn
8,F,African American,1969,M,6,2,Firefox,Google,Gmail,N,Y,N,N,N,Kosong
9,M,White,1987,S,12,1,Safari,Yahoo,Yahoo,Y,Y,Y,Y,N,MySpace
10,F,Hispanic,1959,D,12,5,Chrome,Google,Gmail,Y,N,N,Y,N,Google+